[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

runner = ".cargo/runner.sh"

[build]
target = "riscv32imc-unknown-none-elf"

[alias]
emulate = "run -- -s pty"