[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]
runner = [ 
  "qemu-system-riscv32",
  "-M", "virt",
  "-cpu", "rv32",
  "-smp", "1",
  "-m", "64K",
  "-display", "none",
  "-bios", "none",
  "-serial", "stdio",
  "-kernel", # Cargo will pass the path to the file as last argument
]

[build]
target = "riscv32imc-unknown-none-elf"